tap "argon/mas"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "cask"
brew "colordiff"
brew "cpanminus"
brew "ctags"
brew "fswatch"
brew "git"
brew "htop"
brew "hub"
brew "jq"
brew "mas"
brew "mysql"
brew "node-build"
brew "ndenv"
brew "peco"
brew "pipenv"
brew "pipx"
brew "pyenv"
brew "pyenv-virtualenv"
brew "reattach-to-user-namespace"
brew "scala"
brew "terminal-notifier"
brew "tmux"
brew "tree"
brew "zplug"

cask "biscuit"
cask "deepl"
cask "docker"
cask "font-jetbrains-mono"
cask "font-ricty-diminished"
cask "google-cloud-sdk"
# not working on mba m2. install manually
# cask "google-japanese-ime"
cask "hammerspoon"
cask "iina"
cask "intellij-idea-ce"
cask "iterm2"
cask "keycastr"
cask "licecap"
# not available
# cask "mapture"
cask "ngrok"
cask "notion"
cask "pycharm-ce"
cask "raycast"
cask "skitch"
cask "visual-studio-code"

# 時間かかりすぎるため手動に切り替え
# mas "CopyLess 2", id: 99384101
# mas "Xcode", id: 497799835
